version: '3.8'

services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./server:/service
    environment:
      - DB_HOST=db
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass


  redis:
    image: redis:7.0-alpine
    hostname: redis


  worker:
    build:
        context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./server:/service
    links:
      - redis
    depends_on:
      - redis
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

  flower:
    build:
        context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./server:/service
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"